const sleepTips = [
    "Avoid the screen. This is likely the #1 thing you can do to improve your sleep quality immediately. The artificial “blue” light emitted by electronic screens trigger your body to produce more daytime hormones (like cortisol) and disorient your body's natural preparation for sleep.",
    "Get more sunlight during the day. One of the most vital things that induces great sleep is your body's natural secretion of a hormone called melatonin. Melatonin is produced by the pineal gland in your brain and sends a signal to regulate the sleep-wake cycle in your body.",
    "Have a caffeine curfew. Caffeine is a powerful nervous system stimulant. If your nervous system is lit up, you can forget about getting high quality sleep. Set an unbreakable curfew stop time to make sure that your body has time to remove it from your system. For most people, it's generally going to be before 4 p.m. But if you're really sensitive to caffeine, then you might want to make your curfew even earlier, or possibly avoid caffeine altogether.",
    "Be cool. I remember that during ridiculously hot summers, my parents wouldn't turn the air conditioner up to “save” on the utility bill. Well, I can tell you that I sweated off a lot of pounds those summers tossing and turning in my bed upstairs (oh, and heat rises by the way) trying to sleep through the heat.",
    "Get to bed at the right time. This is key! You can literally get amplified benefits of sleep by sleeping at the right hours. It's been shown that humans get the most significant hormonal secretions and recovery by sleeping during the hours of 10 pm and 2 am. This is what I call “Money Time”.",
    'Use high quality magnesium. Magnesium is a bonafide anti-stress mineral. It helps optimize circulation and blood pressure, balance blood sugar, relax tense muscles, reduce pain, and calm the nervous system. Yet, because it has so many functions, it tends to get depleted from our bodies rather fast.',
    "Get it blacked out. It's a well established fact that we sleep better in a dark environment (just check out this EPIC book Lights Out: Sleep, Sugar, and Survival). But yet, so many people aren't taking full advantage of this. Having light sources of any type in your bedroom can disrupt your sleep patterns. And even using an eye mask is not going to be 100% effective for most people. Did you know that your skin actually has receptors that can pick up light? If there's light in your bedroom, your body is picking it up and sending messages to your brain and organs that can interfere with your sleep. The best solution is: Black it out!",
    "Have a high protein, low carb snack close to bed time. If you want to get truly restful sleep, one of the worst things you can do is eat right before bed. Give your body a solid 90 minutes (more is better) before heading off to bed after eating. This is ESPECIALLY true if you're eating carbs because the inherent blood sugar spike will cause a sharp drop in blood sugar later… and if you happen to be asleep when this hypoglycemia hits, it will likely wake you up and give you difficulties falling back asleep.",
];

export default sleepTips;
